language: android
jdk:
  - oraclejdk8
android:
  components:
    - android-23
    - build-tools-23.0.1
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
      - android-sdk-license-.+
before_install:
  - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - export JAVA_HOME=$JAVA7_HOME
script:
   - ./gradlew build connectedCheck
